2023-09-12 07:33:47,726 [INFO] shopapp.views: Rendering shop index
2023-09-12 07:33:48,818 [INFO] shopapp.views: Rendering shop index
2023-09-12 07:45:42,537 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\first_django_project\settings.py changed, reloading.
2023-09-12 07:45:51,781 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-12 08:07:09,707 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\first_django_project\settings.py changed, reloading.
2023-09-12 08:07:26,091 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-12 08:08:03,106 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\first_django_project\settings.py changed, reloading.
2023-09-12 08:08:23,959 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-12 08:08:42,008 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\first_django_project\settings.py changed, reloading.
2023-09-12 08:08:49,109 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-12 15:29:24,824 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\first_django_project\urls.py changed, reloading.
2023-09-12 15:29:32,025 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-12 15:30:01,406 [INFO] shopapp.views: Rendering shop index
2023-09-12 15:30:16,404 [WARNING] django.request: Not Found: /favicon.ico
2023-09-12 15:30:17,847 [WARNING] django.request: Not Found: /favicon.ico
2023-09-25 06:43:56,768 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 06:44:35,600 [WARNING] django.request: Not Found: /
2023-09-25 06:44:39,039 [WARNING] django.request: Not Found: /favicon.ico
2023-09-25 06:48:32,038 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 06:48:38,471 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 06:49:37,182 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py", line 298, in get
    elem = products.data[0]
           ^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'data'
2023-09-25 06:50:25,889 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py", line 298, in get
    elem = products_data[0]
           ^^^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'data'
2023-09-25 06:50:28,982 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 06:50:35,203 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 06:51:20,328 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 06:51:30,385 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 06:51:37,963 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py", line 299, in get
    name = elem["naem"]
           ~~~~^^^^^^^^
KeyError: 'naem'
2023-09-25 06:57:34,778 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 06:57:44,211 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 06:58:46,788 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 06:59:03,466 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 07:05:21,915 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\first_django_project\settings.py changed, reloading.
2023-09-25 07:05:28,750 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 07:05:58,477 [ERROR] django.request: Internal Server Error: /ru/shop/products/export/
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\sentry_sdk\integrations\django\views.py", line 84, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py", line 299, in get
    name = elem["naem"]
           ~~~~^^^^^^^^
KeyError: 'naem'
2023-09-25 07:11:00,055 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 07:11:10,188 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
2023-09-25 07:13:00,391 [INFO] django.utils.autoreload: C:\PyCharm Community Edition 2022.3\python_django_1\first_django_project\shopapp\views.py changed, reloading.
2023-09-25 07:13:25,438 [INFO] django.utils.autoreload: Watching for file changes with StatReloader
